### ISSUE TITLE
Error on every payment

### ISSUE THREAD

**Issue by chrisvidal** [omise/omise-woocommerce#216]
Error Details
=============
An error of type E_ERROR was caused in line 30 of the file /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/exception/OmiseExceptions.php. Error message: Uncaught OmiseNotFoundException: schedule schd_test_5njcfi9aozkzkf10k35 was not found in /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/exception/OmiseExceptions.php:30
Stack trace:
#0 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/res/OmiseApiResource.php(153): OmiseException::getInstance()
#1 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/res/OmiseApiResource.php(53): OmiseApiResource->execute()
#2 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/OmiseSchedule.php(18): OmiseApiResource::g_retrieve()
#3 /var/www/html/wp-content/plugins/omise/includes/admin/views/omise-page-reports.php(38): OmiseSchedule::retrieve()
#4 /var/www/html/wp-content/plugins/omise/includes/class-omise-admin.php(69): include_once('/var/www/html/w...')
#5 /var/www/html/wp-includes/class-wp-hook.php(287): Omise_Admin->page_reporting()
#6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /

**Comment by chrisvidal** [comment]
I have error everyday upon purchase, new one today

```
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 5.5.4
Current plugin: Omise Payment Gateway (version 4.8)
PHP version 7.4.3


Error Details
=============
An error of type E_ERROR was caused in line 30 of the file /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/exception/OmiseExceptions.php. Error message: Uncaught OmiseNotFoundException: schedule schd_test_5njcfi9aozkzkf10k35 was not found in /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/exception/OmiseExceptions.php:30
Stack trace:
#0 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/res/OmiseApiResource.php(181): OmiseException::getInstance()
#1 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/res/OmiseApiResource.php(53): OmiseApiResource->execute()
#2 /var/www/html/wp-content/plugins/omise/includes/libraries/omise-php/lib/omise/OmiseSchedule.php(18): OmiseApiResource::g_retrieve()
#3 /var/www/html/wp-content/plugins/omise/includes/admin/views/omise-page-reports.php(38): OmiseSchedule::retrieve()
#4 /var/www/html/wp-content/plugins/omise/includes/class-omise-admin.php(66): include_once('/var/www/html/w...')
#5 /var/www/html/wp-includes/class-wp-hook.php(287): Omise_Admin->page_reporting()
#6 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters()
#7 /
```

**Comment by aashishgurung** [comment]
We will be closing this issue for now. If you encounter any similar problems in the future or have any additional information to share, please don't hesitate to open a new issue. Thank you for your understanding.
